### ISSUE TITLE
Preprocess class throws IndexOutOfBoundsException after multiple consecutive taptap actions

### ISSUE THREAD

**Issue by euxcet** [euxcet/AutoAction#1]
Edit: Also happened without taptap actions.

Logs:

```
2022-03-07 18:14:32.054 27565-27718/com.example.datacollection E/AndroidRuntime: FATAL EXCEPTION: Timer-3
    Process: com.example.datacollection, PID: 27565
    java.lang.IndexOutOfBoundsException: Index: 64, Size: 64
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.example.contextactionlibrary.data.Preprocess.checkLastNear(Preprocess.java:185)
        at com.example.contextactionlibrary.contextaction.context.ProximityContext.getContext(ProximityContext.java:42)
        at com.example.contextactionlibrary.contextaction.ContextActionContainer$2.run(ContextActionContainer.java:169)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
2022-03-07 18:14:32.111 27565-27565/com.example.datacollection E/RtgSchedManager: endActivityTransaction: margin state not match
2022-03-07 18:14:32.134 27565-27565/com.example.datacollection E/RtgSchedManager: endActivityTransaction: margin state not match
```

Edit: Another exception:

```
2022-03-08 00:26:32.178 32465-457/com.example.datacollection E/AndroidRuntime: FATAL EXCEPTION: Timer-1
    Process: com.example.datacollection, PID: 32465
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at com.example.contextactionlibrary.data.Preprocess.checkLastNear(Preprocess.java:185)
        at com.example.contextactionlibrary.contextaction.context.ProximityContext.getContext(ProximityContext.java:42)
        at com.example.contextactionlibrary.contextaction.ContextActionContainer$2.run(ContextActionContainer.java:204)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
```

**Comment by euxcet** [comment]
Solved.
